In [1]:
print("hello")

hello


In [12]:
import numpy as np

a = [[1, 2, 3], [11, 22, 33]]
A = np.array(a)

X=np.array([[1,0,1],[2,2,2]]) 
out=X[0:2,2]
out

X=np.array([[1,0],[0,1]])
Y=np.array([[2,1],[1,2]]) 
Z=np.dot(X,Y)
print(Z)

[[2 1]
 [1 2]]


In [10]:
print(2 * A)

[[ 2  4  6]
 [22 44 66]]
